version: "3"
services:
  postgres:
    image: juliomoralez/postgres:latest
    network_mode: bridge
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cinema
    restart: unless-stopped
  springbootapp:
    image: juliomoralez/cinema:latest
    network_mode: bridge
    container_name: cinema
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
  angularapp:
    image: juliomoralez/cinemaang:latest
    network_mode: bridge
    container_name: cinemaang
    expose:
      - 4200
    ports:
      - 4200:80
    restart: unless-stopped
volumes:
  postgres-data: